// Author: Ahmed Badawi

/*
THERE ARE TWO MIXINS NAMED ELECTRICVARIANT AND PETROLVARIANT.

THE ELECTRICVARIANT MIXIN HAS A METHOD ELECTRICVARIANT()
AND THE PETROLVARIANT MIXIN HAS A METHOD PETROLVARIANT(). 

THE CAR CLASS USES BOTH THE ELECTRICVARIANT AND 
PETROLVARIANT MIXINS.
*/